import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";

export type Language = "zh-CN" | "en-US";
export type ThemeMode = "light" | "dark" | "system";

type Dictionary = Record<string, string>;

const dictionaries: Record<Language, Dictionary> = {
  "zh-CN": {
    "common.back": "返回",
    "common.confirm": "确认",
    "patch.operation": "修改类型",
    "patch.update": "修改文件",
    "patch.create": "新建文件",
    "patch.delete": "删除文件",
    "patch.deleteConfirm": "确认删除以下文件？应用前会创建恢复检查点。",
    "browser.title": "代码浏览",
    "browser.subtitle": "定位代码，查看符号，再准备修改。",
    "browser.repository": "当前仓库",
    "browser.search": "搜索代码",
    "browser.query": "输入要查找的文本",
    "browser.glob": "文件过滤，例如 *.py",
    "browser.files": "文件树",
    "browser.symbols": "当前文件符号",
    "browser.context": "仓库摘要",
    "browser.entries": "入口文件",
    "browser.tests": "测试目录",
    "browser.config": "配置文件",
    "browser.choose": "选择文件或搜索结果以查看代码。",
    "browser.edit": "准备修改此文件",
    "browser.empty": "添加本地 Git 仓库后即可浏览代码。",
    "browser.noMatches": "没有找到匹配结果。",
    "browser.results": "搜索结果",
    "browser.truncated": "结果已截断，请缩小范围。",
    "browser.large": "当前显示前 3000 行。",
    "browser.line": "行",
    "browser.noSymbols": "此文件未提取到符号。",
    "common.loading": "加载中…",
    "common.retry": "重试",
    "common.refresh": "刷新",
    "common.none": "暂无",
    "common.error": "操作失败，请重试。",
    "history.title": "验证与检查点",
    "history.tests": "测试记录",
    "history.checkpoints": "文件检查点",
    "history.emptyTests": "执行测试后，此处保留各轮的日志和结果。",
    "history.emptyCheckpoints": "应用 Patch 后会自动创建检查点。",
    "history.rollback": "回滚到此处",
    "history.restored": "已恢复",
    "history.confirm": "恢复到此 Patch 应用前，并撤销同一运行中之后的修改？外部修改冲突会阻止回滚。",
    "history.stdout": "标准输出",
    "history.stderr": "错误输出",
    "history.exit": "退出码",
    "history.iteration": "轮次",
    "history.inMemory": "任务、审批、日志与检查点已保存在本地状态目录，重启后仍可查询和回滚。",
    "validation.kind": "验证类型",
    "validation.auto": "项目测试",
    "validation.pytest": "Python 测试",
    "validation.frontend": "前端测试",
    "validation.static": "静态检查",
    "validation.target": "单项测试路径（可选）",
    "validation.cancelled": "已取消",
    "validation.blocked": "策略阻止",
    "validation.not_found": "未找到命令",
    "validation.timed_out": "超时",
    "validation.passed": "通过",
    "validation.failed": "失败",
    "task.filter": "筛选任务状态",
    "task.all": "全部状态",
    "task.noMatch": "没有符合筛选条件的任务。",
    "commit.excluded": "保留在工作区中的其他文件",
    "localExecution": "本地执行",
    "localExecutionDetail": "工作区路径校验 · 命令受控",
    workspace: "工作区",
    tools: "工具",
    overview: "概览",
    taskQueue: "任务队列",
    repositories: "仓库",
    executionRuns: "执行记录",
    approvals: "审批",
    agentSkills: "Agent 技能",
    securityPolicy: "安全策略",
    settings: "设置",
    sandboxReady: "沙箱就绪",
    restrictedNetwork: "Docker · 受限网络",
    noRepository: "暂无仓库",
    addGitRepository: "添加 Git 仓库",
    localWorkspace: "本地工作区",
    closeNavigation: "关闭导航",
    openNavigation: "打开导航",
    apiConnected: "API 已连接",
    apiOffline: "API 离线",
    checkingApi: "正在检查 API",
    search: "搜索",
    commandMenu: "命令菜单",
    controlRoom: "控制中心",
    monday: "星期一",
    buildWithIntent: "有目标地构建。",
    engineeringLoop: "在一个工作区完成完整工程闭环，从问题信号到经过测试、可审查的变更。",
    currentFocus: "当前焦点",
    noActiveTask: "暂无活动任务",
    createTaskToBegin: "创建任务后开始",
    live: "实时",
    activeTasks: "活动任务",
    liveFromApi: "来自 API 的实时数据",
    connectedLocally: "已连接到本地",
    addRepository: "添加仓库",
    successRate: "成功率",
    noCompletedRuns: "暂无完成的执行",
    needsReview: "待审查",
    humanInLoop: "人工参与",
    startTask: "开始任务",
    whatShouldForgeWorkOn: "Forge 要处理什么？",
    taskPromptPlaceholder: "描述代码库中的问题、变更或疑问……",
    taskPromptLabel: "任务描述",
    running: "运行中",
    runTask: "运行任务",
    agentInspect: "Agent 将检查当前工作区",
    sandboxEnforced: "沙箱已启用",
    inFlight: "执行中",
    viewAll: "查看全部",
    noTasks: "暂无任务。从一个小而明确的变更开始。",
    startAnotherTask: "开始另一个任务",
    executionStream: "执行流",
    selectTaskEvents: "选择或创建任务以查看执行事件。",
    liveEvents: "实时",
    openRunConsole: "打开完整执行控制台",
    recordedEvents: "条已记录事件",
    waitingEvents: "等待记录事件",
    validation: "验证",
    testConsole: "测试控制台",
    runTests: "运行测试",
    noOutput: "没有返回输出。",
    outputTruncated: "输出已达到 API 限制并被截断。",
    runDetectedTests: "运行此任务检测到的项目测试命令。",
    changeReview: "变更审查",
    patchPreview: "Patch 预览",
    checkpointed: "已创建检查点",
    patchPath: "Patch 文件路径",
    patchContent: "Patch 文件内容",
    patchPathPlaceholder: "relative/path.py",
    patchContentPlaceholder: "粘贴完整文件内容，预览低风险更新",
    updateOnly: "变更限定于工作区 · 删除需确认",
    working: "处理中",
    previewDiff: "预览差异",
    previewBeforeRepository: "在变更写入仓库前预览完整文件更新。",
    reviewUnifiedDiff: "应用前请审查 unified diff。",
    cancel: "取消",
    applyCheckpoint: "应用并创建检查点",
    branchIsolation: "分支隔离",
    taskBranch: "任务分支",
    createBranchBeforeCommit: "准备提交前先创建任务分支。",
    "recovery.title": "API 曾在此任务执行中重启。请确认要继续，否则只能回滚或取消。",
    "recovery.action": "确认继续",
    branchName: "任务分支名称",
    createBranch: "创建分支",
    commitReview: "提交审查",
    commitPreview: "提交预览",
    localOnly: "仅本地",
    commitMessage: "提交说明",
    commitMessagePlaceholder: "用一行说明这次变更",
    previewCommit: "预览提交",
    noUncommittedChanges: "没有未提交的变更。",
    testsBeforeCommit: "提交前必须通过测试。",
    createCommit: "创建提交",
    requestWriteApproval: "请求写入审批",
    approve: "批准",
    codebasePulse: "代码库脉搏",
    add: "添加",
    noRepositoryConnected: "尚未连接本地仓库。",
    humanInTheLoop: "人工参与",
    needsYourCall: "需要你的决定",
    reviewTaskPlan: "审查任务计划",
    review: "审查",
    noApprovalTasks: "没有等待审批的任务。",
    forgeRunningLocally: "Forge 正在本地运行",
    lastSynced: "刚刚同步 · v0.1 foundation",
    language: "语言",
    theme: "主题",
    light: "浅色",
    dark: "深色",
    system: "跟随系统",
    chinese: "简体中文",
    english: "English",
    preferences: "偏好设置",
    taskCreated: "任务已创建",
    patchPreviewReady: "Patch 预览已就绪",
    patchApplied: "Patch 已应用",
    testsCompleted: "测试已完成",
    checkpointRestored: "检查点已恢复",
    taskCreatedError: "任务创建失败",
    repositoryError: "仓库添加失败",
    eventsError: "执行事件加载失败",
    testsError: "测试执行失败",
    patchPreviewError: "Patch 预览失败",
    patchApplyError: "Patch 应用失败",
    iterationStartError: "编码轮次启动失败",
    repairStartError: "修复轮次启动失败",
    approvalRequestError: "审批请求创建失败",
    approvalDecisionError: "审批决策失败",
    taskStateError: "任务状态更新失败",
    branchError: "任务分支创建失败",
    commitPreviewError: "提交预览失败",
    commitError: "提交创建失败",
    writeApprovalRequestError: "写入审批请求失败",
    writeApprovalDecisionError: "写入审批决策失败",
    cancelTaskConfirm: "确定取消此任务吗？当前检查点仍会保留。",
    unknown: "未知",
    synced: "已同步",
    changes: "处变更",
    taskCreatedEvent: "任务已创建",
    patchPreviewEvent: "Patch 预览已就绪",
    patchAppliedEvent: "Patch 已应用",
    testsCompletedEvent: "测试已完成",
    checkpointRestoredEvent: "检查点已恢复",
    "nav.overview": "概览",
    "nav.tasks": "任务队列",
    "nav.repositories": "仓库",
    "nav.runs": "执行记录",
    "nav.approvals": "审批",
    primaryNavigation: "主导航",
    repositoryPathPrompt: "输入本地 Git 仓库路径",
    patchAppliedSummary: "已创建检查点 {checkpoint}，应用 {files} 个文件",
    iteration: "轮次",
    currentCodingLoop: "当前编码循环",
    repair: "修复",
    resume: "继续",
    startIteration: "开始轮次",
    awaitingApproval: "等待审批",
    requestPlanApproval: "请求计划审批",
    approvePlan: "批准计划",
    pause: "暂停",
    plan: "计划",
    steps: "步骤",
    iterations: "轮次",
    testOutput: "测试输出",
    "risk.low": "低",
    "risk.medium": "中",
    "risk.high": "高",
    "iterationStatus.coding": "编码中",
    "iterationStatus.testing": "测试中",
    "iterationStatus.passed": "通过",
    "iterationStatus.failed": "失败",
    "iterationStatus.pending": "等待中",
    noCommandDetected: "未检测到命令",
    file: "文件",
    files: "个文件",
    bytes: "字节",
    noChangesDetected: "未检测到变更。",
    clean: "干净",
    changed: "处变更",
    branch: "分支",
    ready: "就绪",
    empty: "空",
    previewLocalDiff: "创建任务提交前预览本地差异。",
    failed: "失败",
    done: "完成",
    paused: "已暂停",
    cancelled: "已取消",
    queued: "排队中",
    owner: "所有者",
    now: "现在",
  },
  "en-US": {
    "common.back": "Back",
    "common.confirm": "Confirm",
    "patch.operation": "Operation",
    "patch.update": "Update file",
    "patch.create": "Create file",
    "patch.delete": "Delete file",
    "patch.deleteConfirm": "Delete these files? A recovery checkpoint will be created first.",
    "browser.title": "Repository explorer",
    "browser.subtitle": "Find source, inspect symbols, then prepare a change.",
    "browser.repository": "Repository",
    "browser.search": "Search code",
    "browser.query": "Text to search for",
    "browser.glob": "File filter, e.g. *.py",
    "browser.files": "Files",
    "browser.symbols": "File symbols",
    "browser.context": "Repository context",
    "browser.entries": "Entry points",
    "browser.tests": "Test directories",
    "browser.config": "Configuration",
    "browser.choose": "Select a file or search result to inspect its source.",
    "browser.edit": "Prepare file change",
    "browser.empty": "Add a local Git repository to browse source.",
    "browser.noMatches": "No matching results.",
    "browser.results": "Search results",
    "browser.truncated": "Results are truncated. Narrow your search.",
    "browser.large": "Showing the first 3,000 lines.",
    "browser.line": "Line",
    "browser.noSymbols": "No symbols found in this file.",
    "common.loading": "Loading…",
    "common.retry": "Retry",
    "common.refresh": "Refresh",
    "common.none": "None",
    "common.error": "The operation failed. Please retry.",
    "history.title": "Validation & checkpoints",
    "history.tests": "Validation history",
    "history.checkpoints": "File checkpoints",
    "history.emptyTests": "Run validation to keep each attempt and its output here.",
    "history.emptyCheckpoints": "Applying a patch creates a file checkpoint.",
    "history.rollback": "Restore checkpoint",
    "history.restored": "Restored",
    "history.confirm": "Restore files to before this patch and undo later patches in this run? Conflicting external edits will block restoration.",
    "history.stdout": "Standard output",
    "history.stderr": "Error output",
    "history.exit": "Exit code",
    "history.iteration": "Iteration",
    "history.inMemory": "Tasks, approvals, logs and checkpoints live in the local state directory and survive an API restart.",
    "validation.kind": "Validation type",
    "validation.auto": "Project tests",
    "validation.pytest": "Python tests",
    "validation.frontend": "Frontend tests",
    "validation.static": "Static checks",
    "validation.target": "Optional test file",
    "validation.cancelled": "Cancelled",
    "validation.blocked": "Blocked",
    "validation.not_found": "Command not found",
    "validation.timed_out": "Timed out",
    "validation.passed": "Passed",
    "validation.failed": "Failed",
    "task.filter": "Filter task status",
    "task.all": "All states",
    "task.noMatch": "No tasks match this filter.",
    "commit.excluded": "Other files kept in the worktree",
    "localExecution": "Local execution",
    "localExecutionDetail": "Workspace checks · controlled commands",
    workspace: "Workspace",
    tools: "Tools",
    overview: "Overview",
    taskQueue: "Task queue",
    repositories: "Repositories",
    executionRuns: "Execution runs",
    approvals: "Approvals",
    agentSkills: "Agent skills",
    securityPolicy: "Security policy",
    settings: "Settings",
    sandboxReady: "Sandbox ready",
    restrictedNetwork: "Docker · restricted network",
    noRepository: "No repository",
    addGitRepository: "Add a Git repository",
    localWorkspace: "local workspace",
    closeNavigation: "Close navigation",
    openNavigation: "Open navigation",
    apiConnected: "API connected",
    apiOffline: "API offline",
    checkingApi: "Checking API",
    search: "Search",
    commandMenu: "Command menu",
    controlRoom: "CONTROL ROOM",
    monday: "MONDAY",
    buildWithIntent: "Build with intent.",
    engineeringLoop: "One workspace for the full engineering loop — from issue signal to tested, reviewable change.",
    currentFocus: "Current focus",
    noActiveTask: "No active task",
    createTaskToBegin: "Create a task to begin",
    live: "LIVE",
    activeTasks: "Active tasks",
    liveFromApi: "Live from API",
    connectedLocally: "Connected locally",
    addRepository: "Add a repository",
    successRate: "Success rate",
    noCompletedRuns: "No completed runs",
    needsReview: "Needs review",
    humanInLoop: "Human in loop",
    startTask: "START A TASK",
    whatShouldForgeWorkOn: "What should Forge work on?",
    taskPromptPlaceholder: "Describe an issue, a change, or a question about your codebase...",
    taskPromptLabel: "Task prompt",
    running: "Running",
    runTask: "Run task",
    agentInspect: "Agent will inspect the current workspace",
    sandboxEnforced: "Sandbox enforced",
    inFlight: "IN FLIGHT",
    viewAll: "View all",
    noTasks: "No tasks yet. Start with a small, specific change.",
    startAnotherTask: "Start another task",
    executionStream: "Execution stream",
    selectTaskEvents: "Select or create a task to see its execution events.",
    liveEvents: "Live",
    openRunConsole: "Open full run console",
    recordedEvents: "recorded events",
    waitingEvents: "Waiting for recorded events",
    validation: "VALIDATION",
    testConsole: "Test console",
    runTests: "Run tests",
    noOutput: "No output returned.",
    outputTruncated: "Output truncated at the API limit.",
    runDetectedTests: "Run the detected project test command for this task.",
    changeReview: "CHANGE REVIEW",
    patchPreview: "Patch preview",
    checkpointed: "checkpointed",
    patchPath: "Patch file path",
    patchContent: "Patch file content",
    patchPathPlaceholder: "relative/path.py",
    patchContentPlaceholder: "Paste the complete file content to preview a low risk update",
    updateOnly: "Workspace paths enforced · deletion requires confirmation",
    working: "Working",
    previewDiff: "Preview diff",
    previewBeforeRepository: "Preview a complete file update before it touches the repository.",
    reviewUnifiedDiff: "Review the unified diff before applying.",
    cancel: "Cancel",
    applyCheckpoint: "Apply and checkpoint",
    branchIsolation: "BRANCH ISOLATION",
    taskBranch: "Task branch",
    createBranchBeforeCommit: "Create a task branch before preparing a commit.",
    "recovery.title": "The API restarted while this task was in flight. Confirm before continuing, or roll back or cancel.",
    "recovery.action": "Continue task",
    branchName: "Task branch name",
    createBranch: "Create branch",
    commitReview: "COMMIT REVIEW",
    commitPreview: "Commit preview",
    localOnly: "local only",
    commitMessage: "Commit message",
    commitMessagePlaceholder: "Explain the change in one line",
    previewCommit: "Preview commit",
    noUncommittedChanges: "No uncommitted changes.",
    testsBeforeCommit: "Tests must pass before commit.",
    createCommit: "Create commit",
    requestWriteApproval: "Request write approval",
    approve: "Approve",
    codebasePulse: "CODEBASE PULSE",
    add: "Add",
    noRepositoryConnected: "No local repository connected yet.",
    humanInTheLoop: "HUMAN IN THE LOOP",
    needsYourCall: "Needs your call",
    reviewTaskPlan: "Review task plan",
    review: "Review",
    noApprovalTasks: "No tasks are waiting for approval.",
    forgeRunningLocally: "Forge is running locally",
    lastSynced: "Last synced just now · v0.1 foundation",
    language: "Language",
    theme: "Theme",
    light: "Light",
    dark: "Dark",
    system: "System",
    chinese: "简体中文",
    english: "English",
    preferences: "Preferences",
    taskCreated: "Task created",
    patchPreviewReady: "Patch preview ready",
    patchApplied: "Patch applied",
    testsCompleted: "Tests completed",
    checkpointRestored: "Checkpoint restored",
    taskCreatedError: "Task creation failed",
    repositoryError: "Repository add failed",
    eventsError: "Execution events failed to load",
    testsError: "Tests failed to run",
    patchPreviewError: "Patch preview failed",
    patchApplyError: "Patch apply failed",
    iterationStartError: "Failed to start coding iteration",
    repairStartError: "Failed to start repair iteration",
    approvalRequestError: "Failed to create approval request",
    approvalDecisionError: "Approval decision failed",
    taskStateError: "Failed to update task state",
    branchError: "Failed to create task branch",
    commitPreviewError: "Commit preview failed",
    commitError: "Commit creation failed",
    writeApprovalRequestError: "Failed to request write approval",
    writeApprovalDecisionError: "Failed to decide write approval",
    cancelTaskConfirm: "Cancel this task? The current checkpoint will remain available.",
    unknown: "Unknown",
    synced: "Synced",
    changes: "changes",
    taskCreatedEvent: "Task created",
    patchPreviewEvent: "Patch preview ready",
    patchAppliedEvent: "Patch applied",
    testsCompletedEvent: "Tests completed",
    checkpointRestoredEvent: "Checkpoint restored",
    "nav.overview": "Overview",
    "nav.tasks": "Task queue",
    "nav.repositories": "Repositories",
    "nav.runs": "Execution runs",
    "nav.approvals": "Approvals",
    primaryNavigation: "Primary navigation",
    repositoryPathPrompt: "Enter a local Git repository path",
    patchAppliedSummary: "Checkpoint {checkpoint} created, applied {files} files",
    iteration: "Iteration",
    currentCodingLoop: "Current coding loop",
    repair: "Repair",
    resume: "Resume",
    startIteration: "Start iteration",
    awaitingApproval: "Awaiting approval",
    requestPlanApproval: "Request plan approval",
    approvePlan: "Approve plan",
    pause: "Pause",
    plan: "PLAN",
    steps: "STEPS",
    iterations: "ITERATIONS",
    testOutput: "test output",
    "risk.low": "low",
    "risk.medium": "medium",
    "risk.high": "high",
    "iterationStatus.coding": "coding",
    "iterationStatus.testing": "testing",
    "iterationStatus.passed": "passed",
    "iterationStatus.failed": "failed",
    "iterationStatus.pending": "pending",
    noCommandDetected: "No command detected",
    file: "file",
    files: "files",
    bytes: "bytes",
    noChangesDetected: "No changes detected.",
    clean: "clean",
    changed: "changed",
    branch: "Branch",
    ready: "ready",
    empty: "empty",
    previewLocalDiff: "Preview the local diff before creating the task commit.",
    failed: "Failed",
    done: "Done",
    paused: "Paused",
    cancelled: "Cancelled",
    queued: "Queued",
    owner: "Owner",
    now: "now",
  },
};

const LANGUAGE_KEY = "forge.language";
const THEME_KEY = "forge.theme";

function readLanguage(): Language {
  if (typeof window === "undefined") return "en-US";
  const saved = window.localStorage.getItem(LANGUAGE_KEY);
  if (saved === "zh-CN" || saved === "en-US") return saved;
  return navigator.language.toLowerCase().startsWith("zh") ? "zh-CN" : "en-US";
}

function readTheme(): ThemeMode {
  if (typeof window === "undefined") return "system";
  const saved = window.localStorage.getItem(THEME_KEY);
  return saved === "light" || saved === "dark" || saved === "system" ? saved : "system";
}

type PreferencesContextValue = {
  language: Language;
  theme: ThemeMode;
  setLanguage: (language: Language) => void;
  setTheme: (theme: ThemeMode) => void;
  t: (key: string) => string;
};

const PreferencesContext = createContext<PreferencesContextValue | null>(null);

export function PreferencesProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(readLanguage);
  const [theme, setThemeState] = useState<ThemeMode>(readTheme);
  const [systemDark, setSystemDark] = useState(() => typeof window !== "undefined" && window.matchMedia("(prefers-color-scheme: dark)").matches);

  useEffect(() => {
    window.localStorage.setItem(LANGUAGE_KEY, language);
    document.documentElement.lang = language;
  }, [language]);

  useEffect(() => {
    window.localStorage.setItem(THEME_KEY, theme);
  }, [theme]);

  useEffect(() => {
    const media = window.matchMedia("(prefers-color-scheme: dark)");
    const onChange = () => setSystemDark(media.matches);
    onChange();
    media.addEventListener?.("change", onChange);
    return () => media.removeEventListener?.("change", onChange);
  }, []);

  useEffect(() => {
    const resolved = theme === "system" ? (systemDark ? "dark" : "light") : theme;
    document.documentElement.dataset.theme = resolved;
    document.querySelector('meta[name="theme-color"]')?.setAttribute("content", resolved === "dark" ? "#111313" : "#eef1ed");
  }, [systemDark, theme]);

  const value = useMemo<PreferencesContextValue>(() => ({
    language,
    theme,
    setLanguage: (next) => setLanguageState(next),
    setTheme: (next) => setThemeState(next),
    t: (key) => dictionaries[language][key] ?? dictionaries["en-US"][key] ?? key,
  }), [language, theme]);

  return <PreferencesContext.Provider value={value}>{children}</PreferencesContext.Provider>;
}

export function usePreferences() {
  const value = useContext(PreferencesContext);
  if (!value) throw new Error("usePreferences must be used within PreferencesProvider");
  return value;
}
